/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Alumno;

/**
 *
 * @author USER
 */
public class panelResultados extends javax.swing.JPanel {

    private Alumno alumnoActual;

    public panelResultados() {
        initComponents();
    }

    public void llenarDatos(Alumno alumno) {
        this.alumnoActual = alumno;
        lblNombre.setText(alumno.getNombre());
        lblID.setText(alumno.getMatricula());
        lblPromedio.setText(String.valueOf(alumno.getPromedio()));
        lblEstado.setText(alumno.getEstado().toString());

        if (alumno.getCarrera() != null && !alumno.getCarrera().isEmpty()) {
            lblCarrera.setText(alumno.getCarrera().get(0).detallarInformacionCarrera());
            lblPlan.setText("");
        }

        lblSemestreActual.setText(alumno.getSemestre());
        lblPeriodo.setText("");

        if (alumno.getCarrera() != null && !alumno.getCarrera().isEmpty()) {
            StringBuilder textoMaterias = new StringBuilder("[ ");
            for (int i = 0; i < alumno.getMaterias().size(); i++) {
                textoMaterias.append(alumno.getMaterias().get(i).listarCargaAcademica());
                if (i < alumno.getMaterias().size() - 1) {
                    textoMaterias.append(" | ");
                }

            }
            textoMaterias.append(" ]");
            lblMaterias.setText(textoMaterias.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPlan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDetallesAcademicos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblSemestreActual = new javax.swing.JLabel();
        lblMaterias = new javax.swing.JLabel();
        btnGenerarConstancia = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Periodo:");

        lblPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        lblPeriodo.setText("jLabel5");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Plan:");

        lblPlan.setForeground(new java.awt.Color(0, 0, 0));
        lblPlan.setText("jLabel5");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Detalles Academicos");

        lblDetallesAcademicos.setForeground(new java.awt.Color(0, 0, 0));
        lblDetallesAcademicos.setText("jLabel5");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Promedio:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado:");

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("jLabel5");

        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("jLabel6");

        lblPromedio.setForeground(new java.awt.Color(0, 0, 0));
        lblPromedio.setText("jLabel7");

        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("jLabel8");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Carrera:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Semestre Actual:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Materias Inscritas:");

        lblCarrera.setForeground(new java.awt.Color(0, 0, 0));
        lblCarrera.setText("jLabel5");

        lblSemestreActual.setForeground(new java.awt.Color(0, 0, 0));
        lblSemestreActual.setText("jLabel5");

        lblMaterias.setForeground(new java.awt.Color(0, 0, 0));
        lblMaterias.setText("jLabel5");

        btnGenerarConstancia.setBackground(new java.awt.Color(22, 104, 179));
        btnGenerarConstancia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGenerarConstancia.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarConstancia.setText("GenerarConstancia");
        btnGenerarConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarConstanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblID)
                                    .addComponent(lblNombre)))
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(lblEstado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblPromedio)))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenerarConstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(lblSemestreActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(lblCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblCarrera))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPromedio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblEstado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSemestreActual)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnGenerarConstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaterias)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConstanciaActionPerformed
        Modelo.ConstanciaEstudios nuevaConstancia = new Modelo.ConstanciaEstudios("", new java.util.Date());
        nuevaConstancia.generarFolio();
        nuevaConstancia.estructurarDocumento();

        Vista.ConstanciaGeneradaView panelPDF = new Vista.ConstanciaGeneradaView();

        panelPDF.mostrarDatosPDF(nuevaConstancia, this.alumnoActual);

        Vista.ConstanciaView ventanaPrincipal = (Vista.ConstanciaView) javax.swing.SwingUtilities.getWindowAncestor(this);

        if (ventanaPrincipal != null) {
            ventanaPrincipal.cambiarPanelActualizable(panelPDF);
        }
    }//GEN-LAST:event_btnGenerarConstanciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarConstancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblDetallesAcademicos;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblSemestreActual;
    // End of variables declaration//GEN-END:variables
}
